### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by bbernhard** [GMaxera/QtFacebook#14]
Hi,

this is not really an issue but more a question. I am thinking about using QtFacebook in a closed source app, but unfortunately GPL is very restrictive and forbids that. So I wanted to ask if you are open for a less restrictive license that would allow to use QtFacebook in closed source apps?
I fully understand if you want to stick with that license (as it's your sourcecode ;-)) but wanted to ask before I start working on my own implementation.

Thanks for your time & Have a nice day,
Bernhard

**Comment by GMaxera** [comment]
Use it ! No problem :-)
I wrongly set the license to GPL. I always told to myself to change to LGPL ... but I never did :-)

So, don't worry. You have my permission to take the code and use into closed source app.

**Comment by GMaxera** [comment]
FYI, beware that my library is not compatible with SDK 4.x
And the graph api version used by 3.x SDKs will be removed in August 2017.
So, soon or later you have to migrate my code to Facebook SDK 4.x

**Comment by marco-piccolino** [comment]
Gian,
you might also want to consider MIT or Apache. As you know complying with
LGPL still poses a few issues on iOS.

Best,
Marco

2016-09-01 10:04 GMT+02:00 GMaxera notifications@github.com:

**Comment by bbernhard** [comment]
Thats great to hear...many thanks!  Thanks also for the info regarding the Facebook SDK. As soon as the other parts of the app are done I'll try to start migrating QtFacebook to the newer SDK. I'll create a pull request once I am done :)

@marco-piccolino: could you maybe explain what's the issue with LGPL and iOS? Does iOS not allow to link against LGPL libraries? I am asking because I am also thinking about an iOS port.

Thanks,
Bernhard

**Comment by marco-piccolino** [comment]
@bbernard I'm no expert but from what I understand is that LGPL requires
dynamic linking and letting the user being able to link against other
versions of the library, which is tricky on iOS/App Store. See e.g.:
http://roadfiresoftware.com/2013/08/the-problem-with-using-lgpl-v2-1-code-in-an-ios-app/

2016-09-01 12:05 GMT+02:00 bbernhard notifications@github.com:

**Comment by ildar-gilmanov** [comment]
Hi!
As I understood if a developer uses LGPL library then he has to provide a code to linked with this library, i.e. if  the library is dynamically linked then the developer has to provide his executable file, if the library is statically linked then he has to provide other static libraries or object files of his project.
Here is another link to license comparison: http://choosealicense.com/licenses/

And, @GMaxera , if you agree with LGPL v3, please accept the @ #13 (Update License to LGPL v3 pull request)

**Comment by ildar-gilmanov** [comment]
But MIT, is more appropriate, I think)

**Comment by ildar-gilmanov** [comment]
@GMaxera, if you agree with MIT, then you could merge @ #15 (MIT license pull request)

**Comment by GMaxera** [comment]
merged #15
